version: "3"

services:
  apipokemon:
    container_name: api_pokemon
    image: akeus/pokeapi:1.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - "5000:80"
    networks:
      - net
    depends_on:
      - cache
  
  cache:
    container_name: api_cache
    image: redis:5-alpine
    networks:
      - net

networks:
  net:
    driver: bridge
  