version: "3"

services:
  apipokemon:
    container_name: api_pokemon
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    networks:
      - net
    depends_on:
      - cache
  
  cache:
    container_name: api_cache
    image: redis:5-alpine
    networks:
      - net

networks:
  net:
    driver: bridge
  