version: "3"

services:
  pokemon-api:
    image: akeus/pokeapi:1.0
    container_name: pokeapi-app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:80"
    networks:
      - net
    depends_on:
      - redis
  
  redis:
    image: redis:5-alpine
    container_name: redis-server
    networks:
      - net

  redis-ui:
    image: marian/rebrow
    container_name: rebrow-server
    ports: 
      - "5001:5001"
    networks: 
      - net
    depends_on:
      - redis

networks:
  net:
    driver: bridge
  