apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: custom-pokeapi
  name: pokeapi-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi-cache
  template:
    metadata:
      labels:
        app: pokeapi-cache
    spec:
      containers:
        - name: redis-cache
          image: redis:5-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "20Mi"
              cpu: "20m"    
    